In [2]:
import numpy as np
arr=np.array([34,45,65,76])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

2.3.5


In [26]:
a=[[34,45,67,23,43],[56,67,65,54,33]]
a=np.array(a)
print(a.ndim)
print(a[1,3])
print(a[1,2:4])
print(a.dtype)
print(a.shape)

2
54
[65 54]
int64
(2, 5)


### converting the datatype of the arrays

In [18]:
arr=np.array([34,45,67,54,423,232])
print(f"the data type of this arrays is {arr.dtype}")
arr2=arr.astype('float')
print(f"the data type of this arrays is {arr2.dtype}")

the data type of this arrays is int64
the data type of this arrays is float64


# view and copy

copy ---> dont update the orirginal array.  
view ---> if changes made in the view then they are also reflected in the original array

In [22]:
arr=np.array([34,45,67,54,423,232])
arrr=arr.copy()
arrr[0]=78213162893
print(arr)
print(arrr)
print(arr.base)
print(arrr.base)

[ 34  45  67  54 423 232]
[78213162893          45          67          54         423         232]
None
None


In [25]:
arr_1=np.array([34,45,67,54,423,232])
arr_2=arr.view()
arr_2[0]=78213162893
print(arr_1)
print(arr_2)
print(arr_1.shape)

[ 34  45  67  54 423 232]
[78213162893          45          67          54         423         232]
(6,)


## reshaping the array

In [31]:
arr_3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_3=arr_3.reshape(3,2,2)

In [33]:
# flatenning means converting the any dimensional array into 1-D
print(arr_3.shape)
arr_4=arr_3.flatten()
print(arr_4)

(3, 2, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### iterating over the arrays

In [34]:
arr_5=[[34,45,67,23,43],[56,67,65,54,33]]
for x in arr_5:
    for y in x:
        print(y)

34
45
67
23
43
56
67
65
54
33


## joining different arrays

concatinate is just adding the new array at the end of the first array.  
stack is putting a new array at the new axis .  
hstack function is used to stack across the rows.  
vstack function is used to stack across the columns

In [37]:
arr_6=np.array([3,4,5,56,67,7])
arr_7=np.array([23,34,64,67,6,88])
print(np.concatenate((arr_6,arr_7)))

[ 3  4  5 56 67  7 23 34 64 67  6 88]


In [42]:
arr_8=np.array([3,4,5,56,67,7])
arr_9=np.array([23,34,64,67,6,88])
print(np.stack((arr_8,arr_9),axis=0))

[[ 3  4  5 56 67  7]
 [23 34 64 67  6 88]]


# spliting the arrays
its the opposite of the joining.Means it breaks a single array into the multiple parts

In [44]:
arr_10 = np.array([1, 2, 3, 4, 5, 6])
print(np.array_split(arr_10,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [46]:
# returns the index where its located
arr_11=np.array([4,5,42,312,765,32,7,32,3])
print(np.where(arr_11==42))
print(np.sort(arr_11))

(array([2]),)
[  3   4   5   7  32  32  42 312 765]
